name: Build Cairocffi
on: [push]

jobs:
  tests:
    name: Build Windows wheel
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: ['x64','x86']
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: ${{ matrix.architecture }}

      - name: Install Wheel and Cairo
        run: |
          #TODO: Change below URL on new cairo release
          curl -L https://github.com/preshing/cairo-windows/releases/download/with-tee/cairo-windows-1.17.2.zip -o cairocomplied.zip
          7z x cairocomplied.zip
          Move-Item 'cairo-windows-*' "cairocomplied"

      - name: Launch tests
        if: runner.os != 'windows'
        run: |
          Copy-Item "$PWD\cairocomplied\lib\x64\cairo.dll" "cairo\cairo.dll"
          python -m pip install wheel
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python setup.py bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
         name: wheels-${{ matrix.python-version }}
         path: dist/cairocffi*.whl